### ISSUE TITLE
Lots of empty blue icons in the drawer

### ISSUE THREAD

**Issue by ctnlaring** [papyros/papyros-shell#170]
The first three pages of my drawer are full of blank blue icons without names.

**Comment by iBelieve** [comment]
I've been experiencing this issue as well, and realized it's because we're setting the icon theme from our own settings file, with the default being Paper, so if you don't have Paper installed, it'll do odd things.

To change the icon theme, edit the `~/.config/papyros-shell` file like this:

```
[desktop]
iconTheme = MaterialOS
```

That being said, if you change the icon theme in Papyros or install Paper, and still see some icons not working, please file a bug report or reopen this issue, as there's a chance the Qt icon loading method might not catch some edge cases (I had to specifically handle icons that are full file names instead of just icon names, for example).
