### ISSUE TITLE
Material Design window decorations for Qt apps

### ISSUE THREAD

**Issue by iBelieve** [papyros/papyros-shell#98]

**Comment by iBelieve** [comment]
This may not be necessary with the server-side window decorations, so re-targetting for version 0.2.

**Comment by iBelieve** [comment]
This turned out to be easier than server-side decorations, so we'll implement this in v0.1

**Comment by iBelieve** [comment]
Almost done, code is in https://github.com/papyros/papyros-shell/tree/feature/98_csd_decorations and https://github.com/papyros/qml-material/tree/feature/csd_decorations.

Upstream bug we need to be fixed to implement a work-around for window shadows: greenisland/greenisland#97

**Comment by IdrissDimson** [comment]
cool

**Comment by IdrissDimson** [comment]
@iBeliever what's the status on this? does the upstream bug still need to be implemented for this to work?

**Comment by iBelieve** [comment]
@VirusKA I haven't looked into a workaround yet, so as of now, yes, we still need that bug to be fixed. Plus, we'll need to wait for v0.7.0 to be released, as I want to stick to stable releases now.

**Comment by IdrissDimson** [comment]
ok. so we wait.

**Comment by M4SSD35TRUCT10N** [comment]
@iBeliever I'm new here I know, but does it make sense to halt the reachment of the milestone by something you can't influence? I suggest to move it to version 0.2 only since it's an enhancement not a bug so far I could investigate. By the way excellent work!

**Comment by IdrissDimson** [comment]
@M4SSD35TRUCT10N it originally was, but michael changed it. It is an enhancement but it's such a big part of the OS that we kinda need it.

**Comment by iBelieve** [comment]
@M4SSD35TRUCT10N The milestone isn't held up by this one issue. I just haven't had much time to work on the shell itself. What little time I do have for Papyros development has been going into packaging and work on our Material framework.

**Comment by M4SSD35TRUCT10N** [comment]
@all No flame war intended. :v: 

@VirusKA I do understand that it is an viral part of the distribution (a unique selling point somehow) but I think getting this done in Version 0.5.6 would also be great since beforehand the community would be able to iron out bugs in other areas. A version under 1.0.0 is always not suitable for production and not final in its features.

@iBeliever Oh, I know your situation too well. I code the whole day here in Germany and the spare time is often eaten up by my wife or other events. What I wanted to say is release early and release often is a much better approach for open software since it adresses the 'greed' of the community to get their hands on stuff. Relying on a third party to adress a problem that is eminent to one self is at least suboptimal and the progress bar of the project is _the_ indicator for any fly-byer that something happens. So I thought to remove the assignment of this issue to 0.1 _and_ 0.2 is a good idea. It's done when it's done but the progress is visible for any milestone (excl. v1.0.0 there this issue must be solved) because of other solvable issues that can be _easily_ timeframed.

I have to deal with a lot of 'projects' in my division (so called 'Gemeindefusion' or 'Gebietsreform') that's why I see that 'problem'. Coming from OpenEdge ABL (awfull) makes it a little bit time consuming for me to get into QML and C/C++ stuff.

**Comment by iBelieve** [comment]
I'm going to move this to v0.2 as we're still waiting for upstream support in GreenIsland to figure out if a window needs server-side decorations.

**Comment by IdrissDimson** [comment]
soo server-side decorations again?

**Comment by iBelieve** [comment]
@VirusKA Nope. Only client side decorations will be supported in v0.1. This means the ugly Qt blue decorations and then Gtk's client-side header bars.

**Comment by iBelieve** [comment]
Based on my conversation with @plfiorini in greenisland/greenisland#154, we'll be using server-side decorations for everything except Gtk windows, which means this ticket (and the work I spent on it) is no longer necessary.
